cmake_minimum_required(VERSION 3.12)
project(libstrophe)
include(GNUInstallDirs)
include(flags OPTIONAL)
if(DEFINED XP_NAMESPACE)
  set(nameSpace NAMESPACE ${XP_NAMESPACE}::)
endif()
if(NOT DEFINED XP_INSTALL_CMAKEDIR)
  set(XP_INSTALL_CMAKEDIR ${CMAKE_INSTALL_DATADIR}/cmake)
endif()
enable_testing()
set_property(GLOBAL PROPERTY USE_FOLDERS ON) # enables MSVC Solution Folders
########################################
if(MSVC)
  add_definitions(
    -D_CRT_NONSTDC_NO_DEPRECATE
    -D_CRT_SECURE_NO_WARNINGS
    -D_WINSOCK_DEPRECATED_NO_WARNINGS
    )
endif()
########################################
if(COMMAND xpFindPkg)
  xpFindPkg(PKGS expat openssl)
else()
  find_package(OpenSSL)
  find_package(EXPAT)
endif()
if(NOT EXPAT_FOUND)
  message(FATAL_ERROR "can't find expat - libstrophe cmake currently hard-coded to use expat")
endif()
if(NOT OPENSSL_FOUND)
  message(FATAL_ERROR "can't find OpenSSL - libstrophe cmake currently hard-coded to use OpenSSL")
endif()
####################
include(CheckLibraryExists)
function(checkLibraryConcat lib symbol liblist)
  string(TOUPPER ${lib} LIB)
  check_library_exists("${lib}" "${symbol}" "" LIBSTROPHE_HAS_${LIB})
  if(LIBSTROPHE_HAS_${LIB})
    list(APPEND ${liblist} ${lib})
    set(${liblist} ${${liblist}} PARENT_SCOPE)
  endif()
endfunction()
checkLibraryConcat(resolv __res_query SYS_LIBS)
checkLibraryConcat(winmm timeGetTime SYS_LIBS)
checkLibraryConcat(ws2_32 getch SYS_LIBS)
########################################
add_subdirectory(src)
add_subdirectory(examples)
add_subdirectory(tests)
install(FILES strophe.h strophepp.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME})
